#!/bin/bash

# Set the target URL
target_url=$1

# Gather endpoints with gau
echo "Gathering endpoints with gau..."
gau $target_url | tee gau_endpoints.txt

# Gather endpoints from Wayback Machine with waybackurls
echo "Gathering endpoints from Wayback Machine with waybackurls..."
waybackurls $target_url | tee waybackurls_endpoints.txt

# Combine the results and sort them
echo "Combining and sorting results..."
cat gau_endpoints.txt waybackurls_endpoints.txt | sort | uniq > all_endpoints.txt

# Extract JS endpoints and write them to a separate file
echo "Extracting JS endpoints..."
grep ".js" all_endpoints.txt > endpoints.js
