#!/usr/bin/sh
subfinder -d $1 -o subdomains.txt 

echo '-----------------------------------------------------'

wc -l subdomains.txt 

cat subdomains.txt | httpx --status-code --follow-redirects --title --silent | tee -a httpx_status.txt
